
# use c as catch-all language
language: c
sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - git clone https://github.com/kuriwaki/linter_test

install:
  - ./travis-tool.sh github_package jimhester/lintr

# Lint
script: 
　- ./travis-linter.sh